name: Medical_Expenses

on: 
  push: 
    braches: ["main"]
  pull_request:
    braches: ["main"]

permission:
  content: read

job: 
  build:
      runs-on: ubuntu-latest

      steps:
          - uses: actions/checkout@v3
          - name: Set up Python 3.12.4
          - uses: actions/checkout@v3
            with:
              python-version: "3.12.4"
