name: Expenses

on:
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: [ ubuntu-latest ]  #self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set Up Python 3.12.4
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.4"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements_docker.txt ]; then pip install -r requirements_docker.txt; fi

      - name: Docker Build and Push to Docker Hub
        run: |
         docker build -t medical .
         docker tag medical vaish18tech/medical:latest
         docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{ secrets.DOCKERHUB_TOKEN }}
         docker push vaish18tech/medical:latest
        env:
          DOCKER_CLI_ACI: 1
      # - name: Lint and Flake8
      #   run:
      #     flake8 . --count --select=E9
        

